application: stage4-submission2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /Images 
  static_dir: Images

- url: /css
  static_dir: css

- url: /.*
  script: HTML-Templates-Stage4.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest